# Main terminal library entry point
# This file includes all the terminal components

require "./terminal/prelude"
require "./terminal/cell"
require "./terminal/messages"
require "./terminal/widget"
require "./terminal/basic_widget"
require "./terminal/input_widget"
require "./terminal/text_box_widget"
require "./terminal/dropdown_widget"
require "./terminal/form_widget"
require "./terminal/table_widget"
require "./terminal/spinner_widget"
require "./terminal/screen_buffer"
require "./terminal/cursor_manager"
require "./terminal/diff_renderer"
require "./terminal/input_provider"
require "./terminal/event_loop"
require "./terminal/widget_manager"
require "./terminal/convenient_dsl"
require "./terminal/input_handler"
require "./terminal/terminal_application"
require "./terminal/interactive_streaming_ui"
require "./terminal/color_dsl"
require "./terminal/container"
require "./terminal/layout_dsl"
require "./terminal/chat_interface_dsl"
require "./terminal/service_provider"
require "./terminal/application_dsl"
require "./terminal/dsl_convenience"
